apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      labels:
        app: app4
    spec:
      containers:
      - name: react-container
        image: app4
        ports:
        - containerPort: 80